version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    ports:
      - 3000:3000
    tty:
      true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
volumes:
  node_modules: {}
